stages:
  preprocess:
    cmd: >-
      python -m src.data_preparation.phase_1_cleaning
      --input data/raw/daisy_dataset_spam_detection.csv
      --output data/processed/clean.csv
      --text-col text
      --label-col label
      --encoding utf-8
    deps:
      - data/raw/daisy_dataset_spam_detection.csv
      - src/data_preparation/preprocess.py
      - src/data_preparation/phase_1_cleaning.py
    outs:
      - data/processed/clean.csv

  split:
    cmd: >-
      python -m src.data_preparation.phase_2_splitting
      --input data/processed/clean.csv
      --train data/dataset/train.csv
      --test data/dataset/test.csv
      --label-col label
      --test-size 0.2
      --random-state 42
    deps:
      - data/processed/clean.csv
      - src/data_preparation/preprocess.py
      - src/data_preparation/phase_2_splitting.py
    outs:
      - data/dataset/train.csv
      - data/dataset/test.csv

  train:
    foreach: ${train.models}
    do:
      cmd: >-
        python -m src.modeling.phase_3_training
        --model ${item}
        --train data/dataset/train.csv
        --model-out models/${item}.joblib
        --metrics-out reports/metrics/${item}.json
        --label-col label
        --max-features 3000
        --cv-folds 5
        --random-state 42
      deps:
        - data/dataset/train.csv
        - data/dataset/test.csv
        - src/modeling/phase_3_training.py
      outs:
        - models/${item}.joblib
      metrics:
        - reports/metrics/${item}.json:
            cache: false