[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "message_guard"
version = "0.0.1"
description = "Spam detection ML system with spam detection, summarization, and automated feedback loops."
authors = [
  { name = "Carles Aguilera, Alex Bueno, Joel Delgado, Berta Torrents, Diego Velilla" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["message_guard"]
include = ["pyproject.toml", "message_guard/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["message_guard"]
force-sort-within-sections = true

